# Generated by Django 4.0.3 on 2022-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100, verbose_name='Tên SP')),
                ('ProductStar', models.IntegerField(verbose_name='Sao SP')),
                ('ProductBrand', models.CharField(max_length=100, verbose_name='Hãng SP')),
                ('ProductNumber', models.IntegerField(verbose_name='S.Lượng SP')),
                ('ProductNewPrice', models.IntegerField(verbose_name='Giá mới SP')),
                ('ProductOldPrice', models.IntegerField(verbose_name='Giá cũ SP')),
                ('ProductImage1', models.CharField(max_length=1000, verbose_name='Ảnh SP 1')),
                ('ProductImage2', models.CharField(max_length=1000, verbose_name='Ảnh SP 2')),
                ('ProductImage3', models.CharField(max_length=1000, verbose_name='Ảnh SP 3')),
                ('ProductRam', models.IntegerField(verbose_name='Ram')),
                ('ProductRom', models.IntegerField(verbose_name='Rom')),
            ],
        ),
    ]
